### PR TITLE
Enable "Source" quality

### PR DESCRIPTION
**Pull request by derrod**
This change makes source quality available in the app.
This might not work on every device, but newer ones (e.g. Nexus 7) should be fine.

### CODE REVIEW

**Comment by hayksaakian** [comment]
i'll merge if you add code that uses that version only when it should be supported (my nexus 7 works with source as well, but not sure what else does)

**Comment by derrod** [comment]
I don't know if there is a clear indicator if a device supports playback of a source stream, it also depends on the broadcasters settings. In this case it is just one and If he doesn't change his settings it should be working, but I don't know if or how I could check if a device supports playback of the stream.

**Comment by hayksaakian** [comment]
you'd want to look at one of the m3u8 files and see what kind of encoding the source stream is in

then check what versions of android can support that encoding

**Comment by hayksaakian** [comment]
works fine on all my devices.

If it's broken for somebody, report it here.

**Pull request merged**
